[package]
name = "dofus-helpers"
version = "2.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
hex = "0.4.3"
log = "0.4.17"
regex = "1.7.3"
sysinfo = "0.28.4"
winapi = "0.3.9"
